version: '2'

services:
  cruftflake:
    image: interpalsnet/cruftflake:1.0.1

    restart: always

    mem_limit: 128m
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  uploaderd:
    build: .
    environment:
      NEWRELIC_LICENSE_KEY: ${NEWRELIC_LICENSE_KEY}
      NEWRELIC_APP_NAME: "UploaderD@stage"

      # Common
      JWT_SECRET: ${INTERPALS_JWT_SECRET}
      CRUFTFLAKE_ADDR: "tcp://cruftflake:5599"

      # DB
      DB_ADDR: ${INTERPALS_DB_ADDR}

      # S3 configuration
      S3_PHOTO_ACCESS_KEY: ${INTERPALS_S3_PHOTO_ACCESS_KEY}
      S3_PHOTO_SECRET_KEY: ${INTERPALS_S3_PHOTO_SECRET_KEY}
      S3_PHOTO_REGION: ${INTERPALS_S3_PHOTO_REGION}
      S3_PHOTO_BUCKET: ${INTERPALS_S3_PHOTO_BUCKET}
    ports:
      - "8989:8989"

    links:
      - cruftflake

    depends_on:
      - cruftflake

    restart: always

    mem_limit: 1024m
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
